//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace WeatherApp.Resources
{
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings()
        {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WeatherApp.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Weather App.
        /// </summary>
        public static string AppTitle
        {
            get
            {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Could not retrieve weather information..
        /// </summary>
        public static string CouldNotRetrieveWeatherInfo
        {
            get
            {
                return ResourceManager.GetString("CouldNotRetrieveWeatherInfo", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description
        {
            get
            {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to EnterCity.
        /// </summary>
        public static string EnterCity
        {
            get
            {
                return ResourceManager.GetString("EnterCity", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Could not retrieve weather information..
        /// </summary>
        public static string ErrorMessage
        {
            get
            {
                return ResourceManager.GetString("ErrorMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Get Weather.
        /// </summary>
        public static string GetWeather
        {
            get
            {
                return ResourceManager.GetString("GetWeather", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Humidity:.
        /// </summary>
        public static string Humidity
        {
            get
            {
                return ResourceManager.GetString("Humidity", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        public static string LoadingMessage
        {
            get
            {
                return ResourceManager.GetString("LoadingMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Note about language.
        /// </summary>
        public static string NoteAboutLanguage
        {
            get
            {
                return ResourceManager.GetString("NoteAboutLanguage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No weather data available..
        /// </summary>
        public static string NoWeatherData
        {
            get
            {
                return ResourceManager.GetString("NoWeatherData", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No Weather Data Available.
        /// </summary>
        public static string NoWeatherDataAvailable
        {
            get
            {
                return ResourceManager.GetString("NoWeatherDataAvailable", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Select Language.
        /// </summary>
        public static string SelectLanguage
        {
            get
            {
                return ResourceManager.GetString("SelectLanguage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Temperature:.
        /// </summary>
        public static string Temperature
        {
            get
            {
                return ResourceManager.GetString("Temperature", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Weather Icon.
        /// </summary>
        public static string WeatherIcon
        {
            get
            {
                return ResourceManager.GetString("WeatherIcon", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Weather in.
        /// </summary>
        public static string WeatherIn
        {
            get
            {
                return ResourceManager.GetString("WeatherIn", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Weather Info Not Available.
        /// </summary>
        public static string WeatherInfoNotAvailable
        {
            get
            {
                return ResourceManager.GetString("WeatherInfoNotAvailable", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Wind Speed.
        /// </summary>
        public static string WindSpeed
        {
            get
            {
                return ResourceManager.GetString("WindSpeed", resourceCulture);
            }
        }
    }
}
